import type { Column, Field, Input, List, Nullable, Select } from '../type';
export declare const isSelectMonth: (field: Field) => boolean;
export declare const isSelectYear: (field: Field) => boolean;
export declare const isCheckbox: (field: Field) => field is Input;
export declare const isInput: (field: Field) => field is Input;
export declare const isRadio: (field: Field) => field is Select;
export declare const isSelect: (field: Field) => field is Select;
export declare const isTextArea: (field: Field) => field is Input;
export declare const isText: (field: Field) => field is Input;
export declare const isEmail: (field: Field) => field is Input;
export declare const isNumber: (field: Field) => field is Input;
export declare function isClickable(field: Field): boolean;
export declare function isList(slot: Field | Column | List): slot is List;
export declare function isColumn(slot: Field | Column | List): slot is Column;
export declare function isField(slot: Field | Column | List): slot is Field;
export declare function isOptions(field: Field): field is Select;
export declare function isTextable(field: Field): boolean;
export declare function isValidValue<T>(value?: Nullable<T>): boolean;
