import { z } from 'zod';
import type { CustomValidation, Field, Input, Schemas, ZodSchema } from '../type';
export declare function buildSchema(schemas: Schemas, fields?: Field[], translations?: Record<string, string>): ZodSchema;
export declare function flatten(error: z.ZodError<Record<string, unknown>>): Record<string, string[]>;
export declare function getSchema(input: Input, translations?: Record<string, string>): z.ZodType<unknown, unknown, z.core.$ZodTypeInternals<unknown, unknown>>;
export declare function getEmail(input: Input, translations?: Record<string, string>): z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodPipe<z.ZodString, z.ZodEmail>> | z.ZodNullable<z.ZodUnion<[z.ZodPipe<z.ZodString, z.ZodEmail>, z.ZodLiteral<"">]>>;
export declare function getBoolean(input: Input, translations?: Record<string, string>): z.ZodPipe<z.ZodTransform<{} | undefined, unknown>, z.ZodCoercedBoolean<unknown>> | z.ZodNullable<z.ZodCoercedBoolean<unknown>>;
export declare function getRadio(input: Input, translations?: Record<string, string>): z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodCoercedString<unknown>> | z.ZodNullable<z.ZodUnion<[z.ZodCoercedString<unknown>, z.ZodLiteral<"">]>>;
export declare function getText(input: Input, translations?: Record<string, string>): z.ZodPipe<z.ZodTransform<unknown, unknown>, z.ZodCoercedString<unknown>> | z.ZodNullable<z.ZodCoercedString<unknown>>;
export declare function getNumber(input: Input, translations?: Record<string, string>): z.ZodPipe<z.ZodTransform<{} | undefined, unknown>, z.ZodCoercedNumber<unknown>> | z.ZodNullable<z.ZodCoercedNumber<unknown>>;
export declare function getYearSchema(input: Input, translations?: Record<string, string>): z.ZodPipe<z.ZodTransform<{} | undefined, unknown>, z.ZodCoercedNumber<unknown>> | z.ZodNullable<z.ZodCoercedNumber<unknown>>;
export declare function getMonthSchema(input: Input, translations?: Record<string, string>): z.ZodCoercedNumber<unknown> | z.ZodNullable<z.ZodCoercedNumber<unknown>>;
export declare function applyCustomValidation(schema: ZodSchema, fields?: Field[], translations?: Record<string, string>): ZodSchema;
export declare function validateCustom(value: unknown, rules: CustomValidation | Array<CustomValidation>, getValue: (name: string) => unknown, translations?: Record<string, string>): string[];
